#
#
#   ______  _______  ______   ______    _
#  |  ____||__   __||  __  | |  __  |  | |  NE PAS MODIFIER CE FICHIER
#  | |____    | |   | |  | | | |__| |  | |  Si *vraiment* vous souhaitez apporter des modifications à la
#  |____  |   | |   | |  | | |  ____|  |_|  configuration de votre stack Docker, utilisez
#   ____| |   | |   | |__| | | |        _   le fichier docker-compose.override.yml :
#  |______|   |_|   |______| |_|       |_|  https://docs.docker.com/compose/extends/
#
#
#


version: '3'
services:
  sandbox:
    build:
      context: ./.docker/sandbox
    container_name: dfs-sandbox
    volumes:
      - "./sandbox/:/var/www/html/sandbox/"
  bo:
    build:
      context: ./.docker/back-office
    container_name: dfs-bo
    volumes:
      - "./back-office/:/var/www/html/back-office/"
    ports:
      - 9999:80
  api:
    build:
      context: ./.docker/api
    container_name: dfs-api
    volumes:
      - "./api/:/var/www/html/api"
    ports:
      - 9998:80
  db:
    image: mariadb
    container_name: dfs-mysql
    environment:
      MYSQL_DATABASE: cine32
      MYSQL_USER: cine32
      MYSQL_PASSWORD: cine32
      MYSQL_ROOT_PASSWORD: cine32
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dfs-pma
    environment:
      PMA_HOST: db
      PMA_PASSWORD: cine32
      PMA_USER: root
    restart: always
    ports:
      - 9997:80
    volumes:
      - /sessions




















  #
  #  Ce qui suit ne fait pas partie du projet :
  #  C'est la partie "instructions" du module
  #  pédagogique
  #  Il faut y toucher _encore moins_ qu'au reste du fichier.
  #

  instructions:
    image: "nginx:alpine"
    container_name: dfs-instructions
    volumes:
      - "./.instructions/:/usr/share/nginx/html"
    ports:
      - 9996:80
